version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - >
      Rscript -e "install.packages(c('pkgdown','remotes'), repos='https://cloud.r-project.org')"
    - >
      Rscript -e "remotes::install_local('.')"
    - >
      Rscript -e "pkgdown::build_site(override = list(destination = 'docs'))"
