# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - Rscript -e 'install.packages(c("pkgdown","remotes"), repos="https://cloud.r-project.org")'
    - Rscript -e 'remotes::install_local(".")'
    - Rscript -e 'pkgdown::build_site(override = list(destination = "docs"))'

# (Remove the sphinx: block entirely if you're only using pkgdown)
# sphinx:
#   configuration: docs/conf.py
#   # builder: "dirhtml"
#   # fail_on_warning: true

# If you do need Python requirements:
python:
  install:
    - requirements: docs/requirements.txt
