version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    # [same R installation commands as above]
    
    # Build pkgdown site (it will use your _pkgdown.yml automatically)
    - Rscript -e "pkgdown::build_site(override = list(destination = '$READTHEDOCS_OUTPUT/html'))"