name: R tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]          
        r:  ["release"]             

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RCISSVAE_RUN_SLOW: "FALSE"     

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pandoc (needed for pkgdown/roxygen)
        uses: r-lib/actions/setup-pandoc@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r }}
          use-public-rspm: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache Python deps
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python deps 
        if: hashFiles('**/requirements.txt') != ''
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -i https://test.pypi.org/simple/ CISS-VAE

      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::testthat
            any::rcmdcheck
            local::.
          needs: check

      - name: Run tests (testthat)
        run: |
          Rscript -e "sessionInfo()"
          Rscript -e "testthat::test_dir('tests/testthat', reporter = c('summary','fail'))"

      - name: Upload testthat output (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: testthat-logs
          path: |
            tests/testthat/*.R
            tests/testthat/_snaps/**
            ./**/testthat.Rout*
          if-no-files-found: ignore
